[package]
name = "libsolv-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "2.4.2"
libc = "0.2.151"
libsolv-sys = { path = "../libsolv-sys" }
